//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SereneStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataBarang
    {
        public int Id { get; set; }
        public string NamaBarang { get; set; }
        public string HargaBarang { get; set; }
        public string Stok { get; set; }
    }
}
